name: build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-14, macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'sbt'
 
      - name: Build
        run: |
          ./scripts/build.sh
        shell: bash

